FROM node as production-build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build:production

FROM nginx
COPY --from=production-build /app/build /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
