name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19

    - name: Install dependencies
      run: npm install

    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HIREHUB_SSH_HOST_IP }}
        username: ${{ secrets.HIREHUB_SSH_USER }}
        password: ${{ secrets.HIREHUB_SSH_KEY }}
        port: 22
        script: |
          cd /var/www/docker-hirehub/
          docker-compose -f compose.yml up -d --build
