name: Frontend CI/CD

on:
  push:
    branches:
      - main
    pull_request:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master #master
      with:
        host: ${{secrets.HIREHUB_SSH_HOST_IP}} # IP address of the server you wish to ssh into
        key: ${{secrets.HIREHUB_SSH_KEY}} # Private or public key of the server
        username: ${{ secrets.HIREHUB_SSH_USER }} # User of the server you want to ssh into

        script: |
          cd /var/www/docker-hirehub
          docker-compose -f compose.yml up -d --build
